### ISSUE TITLE
no module named 'train'

### ISSUE THREAD

**Issue by rahimentezari** [modelfusion/otfusion#5]
Hi Sidak,
Thanks for such great work and your code. I tried to run one of the samples codes in the readme, but it seems that a ''train' folder is missing. The error prints as "No module named 'train'".

**Comment by sidak** [comment]
Hi Rahim,

Thanks for your interest. Please refer to this https://github.com/sidak/otfusion/issues/1

Let me know in case you have more questions. (I'll close this issue for now).

Best,
Sidak
